name: ASP.NET Core Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core environment
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore NuGet dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Step 5: Run unit tests
      - name: Run unit tests
        run: dotnet test ./UnitTest --configuration Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"